import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Appprovider } from "@/context/AppContext";
import { Blogprovider } from "@/context/BlogContext";
import { SavedBlogProvider } from "@/context/SaveBlogContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Appprovider>
          <Blogprovider>
            <SavedBlogProvider>
          <Navbar />
          {children}
          </SavedBlogProvider>
        </Blogprovider>
        </Appprovider>
      </body>
    </html>
  );
}
